@startuml contentstore take 1

actor client as client

participant "REST API" as api #Gainsboro
database "POSTGRES" as pg #Cyan

header "First take on file store architecture"

queue "RABBIT" as rmq #Orange

participant "NODE 1" as n1 #LightGreen

participant "NODE 2" as n2 #Pink

client --> api : request file
api --> pg : ask file location
pg -> api : [located on server]
api -> client : file
||40||
client --> api : request file
api --> pg : ask file location
pg -> api : [located on node 1]
note right
    if main node fails other
    there will be no way to access other nodes
end note 
api --> rmq : contentstore.node_1.get_file.rpc
rmq --> n1 : file request
n1 -> rmq : binary response
rmq -> api : callback
api -> client : file

@enduml